CREATE DATABASE DB_VENTAS;

CREATE TABLE Roles(
	IdRol INTEGER PRIMARY KEY IDENTITY(1, 1),
	Nombre VARCHAR(50),
	FechaRegistro DATETIME DEFAULT GETDATE()
);

CREATE TABLE Menus(
	IdMenu INTEGER PRIMARY KEY IDENTITY (1, 1),
	Nombre VARCHAR(50),
	Icono VARCHAR(50),
	Url VARCHAR(50)
)

CREATE TABLE MenuRol(
	IdMenuRol INTEGER PRIMARY KEY IDENTITY(1, 1),
	IdMenu INTEGER,
	IdRol INTEGER,
	CONSTRAINT FK_MenuRol_IdMenu FOREIGN KEY (IdMenu) REFERENCES Menus(IdMenu),
	CONSTRAINT FK_MenuRol_IdRol FOREIGN KEY (IdRol) REFERENCES Roles(IdRol)
)

CREATE TABLE Usuarios(
	IdUsuario INTEGER PRIMARY KEY IDENTITY(1, 1),
	NombreCompleto VARCHAR(100),
	Correo VARCHAR(40),
	Clave VARCHAR(40),
	Activo BIT DEFAULT 1,
	FechaRegistro DATETIME DEFAULT GETDATE(),
	IdRol INTEGER,
	CONSTRAINT FK_Usuarios_IdRol FOREIGN KEY (IdRol) REFERENCES Roles(IdRol)
)

CREATE TABLE Categorias(
	IdCategoria INTEGER PRIMARY KEY IDENTITY(1, 1),
	Nombre VARCHAR(50),
	Activo BIT DEFAULT 1,
	FechaRegistro DATETIME DEFAULT GETDATE()
)

CREATE TABLE Productos(
	IdProducto INTEGER PRIMARY KEY IDENTITY(1, 1),
	Nombre VARCHAR(100),
	Stock INTEGER,
	Precio DECIMAL(10, 2),
	Activo BIT DEFAULT 1,
	FechaRegistro DATETIME DEFAULT GETDATE(),
	IdCategoria INTEGER,
	CONSTRAINT FK_Productos_IdCategoria FOREIGN KEY (IdCategoria) REFERENCES Categorias(IdCategoria)
)

CREATE TABLE NumerosDocumento(
	IdNumeroDocumento INTEGER PRIMARY KEY IDENTITY(1, 1),
	UltimoNumero INTEGER NOT NULL,
	FechaRegistro DATETIME DEFAULT GETDATE()
)

CREATE TABLE Ventas(
	IdVenta INTEGER PRIMARY KEY IDENTITY(1, 1),
	NumeroDocumento VARCHAR(40),
	TipoPago VARCHAR(50),
	Total DECIMAL(10, 2),
	FechaRegistro DATETIME DEFAULT GETDATE()
)

CREATE TABLE DetalleVenta(
	IdDetalleVenta INTEGER PRIMARY KEY IDENTITY(1, 1),
	Cantidad INTEGER,
	Precio DECIMAL(10, 2),
	Total DECIMAL(10, 2),
	IdVenta	INTEGER,
	IdProducto INTEGER,
	CONSTRAINT FK_DetalleVenta_IdVenta FOREIGN KEY (IdVenta) REFERENCES Ventas(IdVenta),
	CONSTRAINT FK_DetalleVenta_IdProducto FOREIGN KEY (IdProducto) REFERENCES Productos(IdProducto),
)

ALTER AUTHORIZATION ON DATABASE::DB_VENTAS TO SA;